##[rac_nodes]
##oracle-rac-node1 ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=d:\antigravity\oraex\nprod\infra\.vagrant\machines\oracle-rac-node1\virtualbox\private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'
##
##[rac_nodes:vars]
##ansible_python_interpreter=/usr/bin/python3
##configure_lab_storage=true

[standalone]
# Using local key in WSL (We must copy it here to fix permissions)
oracle-db-01 ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/oraex_standalone.key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[standalone:vars]
ansible_python_interpreter=/usr/bin/python3
configure_lab_storage=true
oracle_install_type=single
