---
# =========================================================================
# 1. Preparação (Pre-Flight)
# -------------------------------------------------------------------------
# 'unzip' é trivial, mas essencial. Sem ele, não abrimos o instalador.
# =========================================================================
- name: Install Unzip (Prereqs)
  dnf:
    name: unzip
    state: present

    # Criamos o diretório onde o software vai morar.
    # Importante: O dono DEVE ser o usuário 'oracle'.
    - name: Create Oracle Home Directory
      file:
        path: "{{ oracle_home }}"
        state: directory
        owner: "{{ oracle_user }}"
        group: oinstall
        mode: '0775'
        recurse: yes

    # =========================================================================
    # 2. Instalação (Deploy Binaries)
    # -------------------------------------------------------------------------
    # Diferente de outros softwares, o Oracle Database 19c é "Unzip & Run".
    # Descompactamos o zip DIRETO no diretório final (ORACLE_HOME).
    # =========================================================================
    - name: Unzip Oracle Database Binaries
      unarchive:
        src: "{{ db_zip }}"
        dest: "{{ oracle_home }}"
        remote_src: yes
        owner: "{{ oracle_user }}"
        group: oinstall
        creates: "{{ oracle_home }}/runInstaller" # Evita rodar de novo se já existir

    # O Response File é nosso "Script de Respostas".
    # Ele diz ao instalador: "Instale a edição Enterprise, não crie banco agora, não instale RAC".
    - name: Generate Response File (Template)
      template:
        src: "templates/db_install.j2"
        dest: "{{ rsp_file_dest }}"
        owner: "{{ oracle_user }}"
        group: oinstall
        mode: '0644'

    # =========================================================================
    # 3. Execução do Instalador (Installer Execution)
    # -------------------------------------------------------------------------
    # Rodamos o 'runInstaller' em modo silencioso (-silent).
    # 'ignorePrereq': Ignoramos check de swap/memória pq estamos num Lab pequeno.
    # 'CV_ASSUME_DISTID': Truque para o Oracle aceitar Oracle Linux 8+ sem reclamar.
    # =========================================================================
    - name: Run Database Setup (Silent)
      become: yes
      become_user: "{{ oracle_user }}"
      environment:
        CV_ASSUME_DISTID: OEL7.6
      shell: |
        {{ oracle_home }}/runInstaller -silent -responseFile {{ rsp_file_dest }} -ignorePrereq -waitforcompletion
      register: db_setup
      # RC 0 = Sucesso Total
      # RC 6 = Sucesso com Avisos (comum em Labs com pouca RAM)
      failed_when: db_setup.rc not in [0, 6]

    # Script pós-instalação que ajusta permissões de binários (setuid) e cria o /etc/oratab.
    # DEVE ser rodado como root.
    - name: Run root.sh
      shell: "{{ oracle_home }}/root.sh"
      register: root_out

    - name: Show Root Execution Output
      debug:
        msg: "{{ root_out.stdout_lines }}"
